version: '3'
services:
  yawoen_mongo:
    container_name: yawoen_mongo
    image: mongo:3.4
    ports:
      - 27017:27017
  yawoen_api:
    container_name: yawoen_api
    environment:
      - "DEBUG=API:*"
    volumes:
      - .:/var/www
    links:
      - yawoen_mongo
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3005:3005
      - 8081:8081
      - 8082:8082